name: Deploy The Graph on Rinkeby

on:
  workflow_call:
    inputs:
      subgraph_name:
        default: swarm-rinkeby
        type: string
        required: true
        description: Specify a subgraph name

  workflow_dispatch:
    inputs:
      subgraph_name:
        type: choice
        description: Are you going to deploy a stable or beta version?
        required: true
        default: swarm-rinkeby
        options:
          - swarm-rinkeby
          - swarm-rinkeby-beta

jobs:
  deploy-rinkeby:
    runs-on: ubuntu-latest
    steps:
      - uses: elviskrop/subgraph/.github/workflows/ci.yml@master
      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          SUBGRAPH_NAME: ${{ inputs.subgraph_name }}
          GRAPH_CONFIG_FILE: "subgraph.rinkeby.yaml"
        run: yarn deploy
