name: Deploy The Graph on Rinkeby

on:
  workflow_call:
    inputs:
      subgraph_name:
        type: string
        required: true
        description: Specify a subgraph name

  workflow_dispatch:
    inputs:
      subgraph_name:
        type: choice
        description: Are you going to deploy a stable or beta version?
        required: true
        options:
          - swarm-rinkeby
          - swarm-rinkeby-beta

jobs:
  deploy-rinkeby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.8
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          SUBGRAPH_NAME: ${{ inputs.subgraph_name }}${{ github.event.inputs.subgraph_name }}
          GRAPH_CONFIG_FILE: "subgraph.rinkeby.yaml"
        run: yarn deploy
