name: Deploy Graph

on:
  push:
    branches: [master]

jobs:
  deploy-rinkeby:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 10
#      - name: Install
#        run: yarn --frozen-lockfile
#      - name: Codegen
#        run: yarn codegen
#      - name: Build
#        run: yarn build
      - name: Authentication
        env:
          ACCESS_TOKEN: ${{secrets.$THE_GRAPH_ACCESS_TOKEN}}
        run: yarn auth
#      - name: Deploy
#        env:
#          GITHUB_USERNAME: ${{github.actor}}
#          SUBGRAPH_NAME: "swarm-rinkeby"
#          GRAPH_CONFIG_FILE: "subgraph.rinkeby.yaml"
#        run: yarn deploy

#      - uses: gtaschuk/graph-deploy@v0.1.0
#        with:
#          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
#          graph_subgraph_name: "swarm-rinkeby"
#          graph_deploy_studio: "false"
#          graph_account: ${{github.actor}}
#          graph_config_file: "subgraph.rinkeby.yaml"
