name: Deploy Stable Graphs

on:
  push:
    branches: [ master ]

jobs:
    deploy-stable-rinkeby:
      uses: elviskrop/subgraph/.github/workflows/graph.rinkeby.yml@master
      with:
        SUBGRAPH_NAME: swarm-rinkeby
        GRAPH_ACCESS_TOKEN: ${{ secrets.GRAPH_ACCESS_TOKEN }}
#  deploy-rinkeby:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12.22.8
#      - name: Install dependencies
#        run: yarn --frozen-lockfile
#      - name: Codegen
#        run: yarn codegen
#      - name: Build
#        run: yarn build
#      - name: Deploy
#        env:
#          ACCESS_TOKEN: ${{secrets.GRAPH_ACCESS_TOKEN}}
#          GITHUB_USERNAME: ${{github.actor}}
#          SUBGRAPH_NAME: "swarm-rinkeby"
#          GRAPH_CONFIG_FILE: "subgraph.rinkeby.yaml"
#        run: yarn deploy
